// BOM (Bill of Materials) export — generates an HTML table from build components.

import type { URDFBuildController, ComponentDef } from './build.js';
import { COMPONENT_CATALOG } from './build.js';

interface BomRow {
    name:     string;
    type:     string;
    category: string;
    qty:      number;
    dims:     string;   // "45 × 20 × 15 mm"
    cssColor: string;
}

const CAT_COLORS: Record<string, string> = {
    Sensor:     'var(--cat-sensor)',
    Actuator:   'var(--cat-actuator)',
    MCU:        'var(--cat-mcu)',
    Power:      'var(--cat-power)',
    Structural: 'var(--cat-structural)',
};

function fmtDims(dims: number[], geomType: string): string {
    if (geomType === 'cylinder') {
        const r = (dims[0] * 1000).toFixed(1);
        const l = (dims[1] * 1000).toFixed(1);
        return `\u00d8${r} × ${l} mm`;
    }
    return dims.map(d => (d * 1000).toFixed(1)).join(' × ') + ' mm';
}

export function generateBomRows(buildCtrl: URDFBuildController): BomRow[] {
    const entries = buildCtrl.getComponentEntries();
    // Aggregate by type
    const counts = new Map<string, { def: ComponentDef; dims: number[]; count: number }>();
    for (const { type } of entries) {
        const def = COMPONENT_CATALOG[type];
        if (!def) continue;
        const existing = counts.get(type);
        if (existing) {
            existing.count++;
        } else {
            counts.set(type, { def, dims: [...def.defaultDims], count: 1 });
        }
    }
    const rows: BomRow[] = [];
    for (const [type, { def, dims, count }] of counts) {
        rows.push({
            name:     def.label,
            type,
            category: def.category ?? 'Other',
            qty:      count,
            dims:     fmtDims(dims, def.geomType),
            cssColor: def.cssColor ?? CAT_COLORS[def.category ?? ''] ?? 'var(--text-3)',
        });
    }
    return rows;
}

export function exportBomHtml(buildCtrl: URDFBuildController): void {
    const rows = generateBomRows(buildCtrl);
    if (rows.length === 0) return;

    const robotName = buildCtrl.robotName || 'robot';
    const rowsHtml = rows.map(r => `
      <tr>
        <td><span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:${r.cssColor};vertical-align:middle;margin-right:6px"></span>${esc(r.name)}</td>
        <td>${esc(r.category)}</td>
        <td style="text-align:center">${r.qty}</td>
        <td style="font-family:ui-monospace,monospace;font-size:0.8em">${esc(r.dims)}</td>
      </tr>`).join('');

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>BOM — ${esc(robotName)}</title>
<style>
  body { font-family: -apple-system, system-ui, sans-serif; background: #0d0f17; color: #e0e4ef; padding: 32px; }
  h1 { font-size: 1.1rem; font-weight: 600; margin-bottom: 4px; }
  .sub { font-size: 0.75rem; color: #888; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; font-size: 0.8125rem; }
  th { text-align: left; font-size: 0.625rem; font-weight: 600; text-transform: uppercase;
       letter-spacing: 0.08em; color: #888; padding: 8px 12px; border-bottom: 1px solid #222; }
  td { padding: 8px 12px; border-bottom: 1px solid #1a1a2a; }
  tr:hover td { background: #141622; }
  .total { font-size: 0.75rem; color: #888; margin-top: 12px; text-align: right; }
</style>
</head>
<body>
  <h1>${esc(robotName)} — Bill of Materials</h1>
  <p class="sub">${rows.length} component types, ${rows.reduce((s, r) => s + r.qty, 0)} total parts</p>
  <table>
    <thead><tr><th>Component</th><th>Category</th><th>Qty</th><th>Dimensions</th></tr></thead>
    <tbody>${rowsHtml}</tbody>
  </table>
  <p class="total">Generated by URDF Studio</p>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const a = Object.assign(document.createElement('a'), {
        href: URL.createObjectURL(blob),
        download: `${robotName}-bom.html`,
    });
    a.click();
    URL.revokeObjectURL(a.href);
}

function esc(s: string): string {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
